version: "3"

networks:
  webmoney:

services:
  prometheus:
    image: prom/prometheus:latest
    networks:
      - webmoney    
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana:latest
    networks:
      - "webmoney"
    ports:
      - "3000:3000"
    volumes:      
      - ./grafana/datasources.yml:/etc/grafana/provisioning/datasources/prometheus.yaml     
  rabbitmq:
    container_name: iq-rabbitmq
    hostname: rabbit
    image: masstransit/rabbitmq:latest
    networks:
      - webmoney
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"
    healthcheck:
        timeout: 5s
        interval: 5s
        retries: 10
  redis:
    image: redis
    networks:
      - webmoney
    container_name: iq-redis
    ports:
      - "6379:6379"
  mongo:
    image: "mongo"
    networks:
      - webmoney
    container_name: iq-mongo
    ports:
      - '27017-27019:27017-27019'
  sqlserver:
    image: "masstransit/sqlserver-quartz"
    container_name: iq-sqlserver
    networks:
      - webmoney
    ports:
      - '14333:1433'
    environment:
      SA_PASSWORD: "WTmrFXm2mT9876IS"
      ACCEPT_EULA: "Y"