// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.1
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace confluent.io.examples.serialization.avro
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.11.1")]
	public partial class ICurrierLeft : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"ICurrierLeft\",\"namespace\":\"confluent.io.examples.seriali" +
				"zation.avro\",\"fields\":[{\"name\":\"Timestamp\",\"type\":\"string\"},{\"name\":\"CurrierId\"," +
				"\"type\":\"string\"}]}");
		private string _Timestamp;
		private string _CurrierId;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return ICurrierLeft._SCHEMA;
			}
		}
		public string Timestamp
		{
			get
			{
				return this._Timestamp;
			}
			set
			{
				this._Timestamp = value;
			}
		}
		public string CurrierId
		{
			get
			{
				return this._CurrierId;
			}
			set
			{
				this._CurrierId = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.Timestamp;
			case 1: return this.CurrierId;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.Timestamp = (System.String)fieldValue; break;
			case 1: this.CurrierId = (System.String)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
