apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-ms-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shop-microservice
  template:
    metadata:
      labels:
        app: shop-microservice
    spec:
      containers:
        - name: shop-microservice
          image: secvbulrep/shop_home:latest
---
apiVersion: v1
kind: Service
metadata:
  name: shop-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: shop-microservice
  ports:
    - port: 80
      protocol: TCP
      name: shop-microservice
      targetPort: 80