apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-ms-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shop-microservice
  template:
    metadata:
      labels:
        app: shop-microservice
    spec:
      containers:
        - name: shop-microservice
          image: secvbulrep/shop:latest