version: "3"
services:
  rabbitmq:
    container_name: iq-rabbitmq
    hostname: rabbit
    image: rabbitmq:3-management
    ports:
     - "5672:5672"
     - "15672:15672"
  redis:
    image: redis
    container_name: iq-redis
    ports:
      - "6379:6379"
  mongo:
    image: "mongo"
    container_name: iq-mongo
    ports:
      - '27017-27019:27017-27019'